"""dynamic_profiles — load profiles from JSON files in a directory.

iTerm2-style: load profile definitions from a directory of JSON files.
Useful for fleet management where profiles are generated by tooling.

Configuration (config.toml):
    [plugins.dynamic_profiles]
    enabled = false                             # default false; opt-in
    profiles_dir = "~/.config/qterminator/profiles.d"  # default

Each JSON file in profiles.d/ should define one or more profiles:
    
    {
        "name": "my-profile",
        "font_family": "JetBrains Mono",
        "font_size": 12,
        "color_scheme": "Solarized Dark",
        "scrollback_lines": 10000,
        "show_titlebar": true
    }
"""

import glob
import json
import os

from PyQt6.QtCore import QFileSystemWatcher

from qterminator import config as config_mod
from qterminator.config import Config
from qterminator.plugin import Plugin


def _default_profiles_dir() -> str:
    """Resolve the default profiles directory lazily so tests that
    monkeypatch ``config_mod.CONFIG_DIR`` see their tmp path."""
    return os.path.join(config_mod.CONFIG_DIR, "profiles.d")


class DynamicProfilesPlugin(Plugin):
    name = "dynamic_profiles"
    description = (
        "Load profile definitions from JSON files in a directory. "
        "Useful for fleet management and generated profiles."
    )
    version = "0.1"
    capabilities = []

    def __init__(self):
        super().__init__()
        self._watcher = None
        self._profiles_dir = None

    def activate(self, app_controller):
        cfg = Config()
        enabled = cfg.get("plugins", "dynamic_profiles", "enabled", default=False)
        if not enabled:
            return
        
        self._profiles_dir = os.path.expanduser(
            cfg.get("plugins", "dynamic_profiles", "profiles_dir",
                  default=_default_profiles_dir())
        )
        
        # Load profiles
        self._load_profiles(cfg)
        
        # Set up file watcher
        self._setup_watcher(cfg)

    def _load_profiles(self, cfg: Config):
        """Load profiles from all JSON files in the directory."""
        if not os.path.isdir(self._profiles_dir):
            return
        
        # Find all JSON files
        pattern = os.path.join(self._profiles_dir, "*.json")
        files = glob.glob(pattern)
        
        for filepath in files:
            self._load_profile_file(cfg, filepath)

    def _load_profile_file(self, cfg: Config, filepath: str):
        """Load a single profile JSON file."""
        try:
            with open(filepath, 'r') as f:
                data = json.load(f)
        except (json.JSONDecodeError, IOError):
            return
        
        # Handle both single profile and array of profiles
        if isinstance(data, list):
            profiles = data
        elif isinstance(data, dict):
            profiles = [data]
        else:
            return
        
        for profile in profiles:
            self._merge_profile(cfg, profile)

    def _merge_profile(self, cfg: Config, profile: dict):
        """Merge a profile into the config.

        Validates the name and refuses to overwrite the built-in
        ``"default"`` profile — a malformed JSON or a malicious file
        could otherwise replace ``default`` for every terminal.
        """
        name = profile.get("name")
        if not isinstance(name, str) or not name or name == "default":
            return

        for key, value in profile.items():
            if key == "name":
                continue
            cfg.set("profiles", name, key, value)

    def _setup_watcher(self, cfg: Config):
        """Set up file system watcher for auto-reload.

        Watches both the directory (catches creates/deletes) and each
        existing JSON file (catches in-place edits on filesystems where
        the directory mtime doesn't change on file-content writes).
        """
        self._watcher = QFileSystemWatcher()

        if os.path.isdir(self._profiles_dir):
            self._watcher.addPath(self._profiles_dir)
            pattern = os.path.join(self._profiles_dir, "*.json")
            files = glob.glob(pattern)
            if files:
                self._watcher.addPaths(files)

        self._watcher.directoryChanged.connect(
            lambda path: self._on_directory_changed(cfg, path)
        )
        self._watcher.fileChanged.connect(
            lambda path: self._on_file_changed(cfg, path)
        )

    def _on_directory_changed(self, cfg: Config, path: str):
        """Called when directory contents change. Re-add any new files
        to the watch list so subsequent in-place edits also fire."""
        self._load_profiles(cfg)
        if self._watcher is not None and os.path.isdir(self._profiles_dir):
            tracked = set(self._watcher.files())
            pattern = os.path.join(self._profiles_dir, "*.json")
            new = [f for f in glob.glob(pattern) if f not in tracked]
            if new:
                self._watcher.addPaths(new)

    def _on_file_changed(self, cfg: Config, path: str):
        """Called when a profile file changes.

        Many editors save via rename (unlink + create), which makes
        QFileSystemWatcher drop the path from its set. If the file
        still exists after the change, re-add it to the watcher so
        the next edit still fires.
        """
        if not path.endswith(".json"):
            return
        self._load_profile_file(cfg, path)
        if (
            self._watcher is not None
            and os.path.exists(path)
            and path not in self._watcher.files()
        ):
            self._watcher.addPath(path)

    def deactivate(self):
        if self._watcher is not None:
            self._watcher.deleteLater()
            self._watcher = None

    def reload(self, cfg: Config = None):
        """Manually reload all profiles."""
        if cfg is None:
            cfg = Config()
        self._load_profiles(cfg)
